---
- hosts: all
  name: Mac Setup
  gather_facts: no
  vars_files:
    - vars/config.yml
  pre_tasks:
    - name: Include Pre-installation Checks
      include_tasks: tasks/pre-checks.yml
    - name: Gather facts
      setup:
  tasks:
    - name: Include Development Tools Installation
      include_tasks: tasks/dev-apps.yml
      when: install_dev_tools | bool
    - name: Include Browsers and Communication Tools Installation
      include_tasks: tasks/browser-apps.yml
      when: install_browsers | bool
    - name: Include Media Applications Installation
      include_tasks: tasks/media-apps.yml
      when: install_media | bool
    - name: Include Utility Applications Installation
      include_tasks: tasks/utility-apps.yml
      when: install_utilities | bool
    - name: Include Network Tools Installation
      include_tasks: tasks/network-apps.yml
      when: install_network | bool
    - name: Include Custom Applications Installation
      include_tasks: tasks/custom-apps.yml
      when: install_custom_apps | bool
  post_tasks:
    - name: Include System Configuration and Cleanup
      include_tasks: tasks/system-config.yml
