---
# Browsers & Communication Tools Installation
- name: Install Browsers and Communication Tools
  when: install_browsers | bool
  block:
    - name: Install google-chrome
      homebrew_cask:
        name: google-chrome
        state: present

    - name: Install firefox
      homebrew_cask:
        name: firefox
        state: present

    - name: Install discord
      homebrew_cask:
        name: discord
        state: present

    - name: Install telegram
      homebrew_cask:
        name: telegram
        state: present

    - name: Install telegram-alpha
      homebrew_cask:
        name: telegram-alpha
        state: present

    - name: Install whatsapp
      homebrew_cask:
        name: whatsapp
        state: present

    - name: Install zoom
      homebrew_cask:
        name: zoom
        state: present

    - name: Install chatgpt
      homebrew_cask:
        name: chat-gpt
        state: present
