---
# Development Tools Installation
- name: Install Development Tools
  when: install_dev_tools | bool
  block:
    - name: Install Visual Studio Code
      homebrew_cask:
        name: visual-studio-code
        state: present
        version: "{{ vscode_version }}"

    - name: Install Docker
      homebrew_cask:
        name: docker
        state: present
        version: "{{ docker_version }}"

    - name: Install Arduino IDE
      homebrew_cask:
        name: arduino-ide
        state: present

    - name: Install Lens
      homebrew_cask:
        name: lens
        state: present

    - name: Install UTM
      homebrew_cask:
        name: utm
        state: present

    - name: Install Bambu Studio
      homebrew_cask:
        name: bambu-studio
        state: present

    - name: Install Raspberry Pi Imager
      homebrew_cask:
        name: raspberry-pi-imager
        state: present

    - name: Install Orka Desktop
      homebrew_cask:
        name: orka
        state: present

    - name: Install Autodesk Fusion 360
      homebrew_cask:
        name: autodesk-fusion360
        state: present

    # Configure VS Code extensions
    - name: Install VS Code Extensions
      command: code --install-extension {{ item }}
      with_items: "{{ vscode_extensions }}"
      when: vscode_extensions is defined
      ignore_errors: true

    # Configure Git
    - name: Configure Git settings
      git_config:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        scope: global
      with_dict: "{{ git_config }}"
      when: git_config is defined
