---
# System Configuration and Cleanup
- name: Configure System Settings
  block:
    # Security Settings
    - name: Configure Firewall
      command: sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
      when: enable_firewall | bool
      become: true

    # System Preferences
    - name: Set Dock auto-hide
      command: defaults write com.apple.dock autohide -bool {{ dock_autohide | string | lower }}
      when: dock_autohide is defined

    - name: Set Dark Mode
      command: defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"
      when: dark_mode | bool

    - name: Restart Dock to apply changes
      command: killall Dock
      ignore_errors: true

# Cleanup Tasks
- name: Perform Cleanup
  block:
    - name: Cleanup Homebrew
      command: brew cleanup
      changed_when: false

    - name: Remove Homebrew cache
      file:
        path: "~/Library/Caches/Homebrew"
        state: absent

    # Installation Summary
    - name: Get installed package versions
      command: brew list --versions
      register: installed_versions
      changed_when: false

    - name: Display Installation Summary
      debug:
        msg:
          - "Installation Complete!"
          - "Installed Packages:"
          - "{{ installed_versions.stdout_lines }}"
          - "System Configuration:"
          - "- Firewall: {{ enable_firewall }}"
          - "- Dark Mode: {{ dark_mode }}"
          - "- Dock Auto-hide: {{ dock_autohide }}"
