---
# Utility Applications Installation
- name: Install Utility Applications
  when: install_utilities | bool
  block:
    - name: Install The Unarchiver
      homebrew_cask:
        name: the-unarchiver
        state: present

    - name: Install CleanMyMac X
      homebrew_cask:
        name: cleanmymac
        state: present

    - name: Install Stats
      homebrew_cask:
        name: stats
        state: present

    - name: Install Adobe Acrobat Reader
      homebrew_cask:
        name: adobe-acrobat-reader
        state: present

    - name: Install Logi Options+
      homebrew_cask:
        name: logi-options-plus
        state: present

    - name: Install LM Studio
      homebrew_cask:
        name: lm-studio
        state: present

    - name: Install Warp
      homebrew_cask:
        name: warp
        state: present
