---
# Installation toggles
install_dev_tools: true
install_browsers: true
install_media: true
install_utilities: true
install_network: true
install_creative: true

# System Preferences
dock_autohide: true
dark_mode: true

# Security Settings
enable_firewall: true

# Network Settings
dns_servers:
  - "1.1.1.1"
  - "1.0.0.1"

# Package versions
vscode_version: latest
docker_version: latest

# Development Tools Configuration
vscode_extensions:
  - "ms-python.python"
  - "golang.go"
  - "dbaeumer.vscode-eslint"
  - "redhat.ansible"

git_config:
  core.editor: "code --wait"
  pull.rebase: "false"
  init.defaultBranch: "main"
