---
# Installation toggles
install_dev_tools: true
install_browsers: true
install_media: true
install_utilities: true
install_network: true
install_creative: true
install_custom_apps: false  # Custom apps installation disabled by default

# Custom Apps Configuration
# Uncomment and modify these as needed
# custom_app_name: "YourApp"
# custom_app_url: "https://example.com/YourApp.dmg"
# custom_pkg_name: "YourPackage"
# custom_pkg_url: "https://example.com/YourPackage.pkg"
# custom_zip_name: "YourZipApp"
# custom_zip_url: "https://example.com/YourZipApp.zip"

# System Preferences
dock_autohide: true
dark_mode: true

# Security Settings
enable_firewall: true

# Network Settings
dns_servers:
  - "1.1.1.1"
  - "1.0.0.1"

# Package versions
vscode_version: latest
docker_version: latest

# Development Tools Configuration
vscode_extensions:
  - "ms-python.python"
  - "golang.go"
  - "dbaeumer.vscode-eslint"
  - "redhat.ansible"

git_config:
  core.editor: "code --wait"
  pull.rebase: "false"
  init.defaultBranch: "main"
